language: go

go:
  - master
  - 1.7.x

notifications:
  email: false

before_install:
  - go get -t -v ./...

script:
  - go test -v -race ./...
  - go vet ./...
  - go build -o binary/link022_agent agent/agent.go

after_success:
  - bash <(curl -s https://codecov.io/bash)
